/* Catalogue — mirrors rhums-cigares.ch (WooCommerce store, checked 24.09.2026).
   Prices in CHF incl. VAT. A box always holds 20 cigars at 20 × the single price.
   Coronitas are listed without a price and marked "Nicht vorrätig" on the shop. */

export const SHOP = 'https://rhums-cigares.ch';

export const VITOLAS = [
  // key, display name, smoking time (min), single price, box price, stock
  { key: 'churchill', name: 'Churchill', time: 130, single: 24.5, box: 490, stock: true },
  { key: 'toro',      name: 'Toro',      time: 120, single: 23.0, box: 460, stock: true },
  { key: 'torpedo',   name: 'Torpedo',   time: 80,  single: 19.5, box: 390, stock: true },
  { key: 'gordo',     name: 'Gordo',     time: 25,  single: 17.0, box: 340, stock: true },
  { key: 'robusto',   name: 'Robusto',   time: 40,  single: 16.0, box: 320, stock: true },
  { key: 'corona',    name: 'Corona',    time: 40,  single: 15.0, box: 300, stock: true },
  { key: 'coronita',  name: 'Coronita',  time: 20,  single: null, box: null, stock: false },
];

// image file names as published on the client's site
const IMG = {
  connecticut: { churchill: 'connecticut_churchill', toro: 'connecticut_toro', torpedo: 'connecticut_torpedo', gordo: 'connecticut_fett', robusto: 'connecticut_robust', corona: 'connecticut_corona', coronita: 'connecticut_coronita' },
  habano:      { churchill: 'habano_churchill', toro: 'habano_toro', torpedo: 'habano_torpedo', gordo: 'habano_gordo', robusto: 'habano_robusto', corona: 'habano_corona', coronita: 'habano_coronita' },
  sumatra:     { churchill: 'sumatra_churchill', toro: 'sumatra_toro', torpedo: 'sumatra_torpedo', gordo: 'sumatra_fett', robusto: 'sumatra_robust', corona: 'sumatra_corona', coronita: 'sumatra_coronita' },
  maduro:      { churchill: 'maduro_natural_churchill', toro: 'maduro_natural_toro', torpedo: 'maduro_natural_torpedo', gordo: 'maduro_natural_gordo', robusto: 'maduro_natural_robusto', corona: 'maduro_natural_corona', coronita: 'maduro_natural_coronita' },
};

export const LINES = [
  {
    key: 'connecticut', name: 'Connecticut', slug: 'connecticut', strength: 3,
    blend: { wrapper: 'ni', binder: 'ni', filler: ['ec', 'ni'] },
    // 3D colours: wrapper tint, band field, band ink, foot band
    wrapper: '#c89868', band: '#f4f1ea', ink: '#1b1714', foot: '#d9dadc',
    accent: '#e9e3d6',
  },
  {
    key: 'habano', name: 'Habano', slug: 'habano', strength: 5,
    blend: { wrapper: 'cu', binder: 'br', filler: ['ni'] },
    wrapper: '#9c6a4c', band: '#d8212f', ink: '#ffffff', foot: '#d8212f',
    accent: '#e0413f',
  },
  {
    key: 'sumatra', name: 'Sumatra', slug: 'sumatra', strength: 7,
    blend: { wrapper: 'hn', binder: 'ni', filler: ['mx'] },
    wrapper: '#a8764f', band: '#1e82d2', ink: '#ffffff', foot: '#1e82d2',
    accent: '#4a9be0',
  },
  {
    key: 'maduro', name: 'Maduro Natural', slug: 'maduro-natural', strength: 9,
    blend: { wrapper: 'cu', binder: 'ec', filler: ['mx'] },
    wrapper: '#4a3128', band: '#141210', ink: '#c9a45c', foot: '#141210',
    accent: '#c9a45c',
  },
];

export function productSlug(line, vitola) { return `${line.slug}-${vitola.key}`; }
export function productImg(line, vitola) { return `img/p/${IMG[line.key][vitola.key]}.webp`; }
export function productUrl(line, vitola, lang) {
  return lang === 'de'
    ? `${SHOP}/produkt/${productSlug(line, vitola)}/`
    : `${SHOP}/fr/produit/${productSlug(line, vitola)}/`;
}
export function chf(n) { return 'CHF ' + n.toFixed(2); }

export const COUNTRIES = {
  fr: { ni: 'Nicaragua', cu: 'Cuba', br: 'Brésil', hn: 'Honduras', mx: 'Mexique', ec: 'Équateur' },
  de: { ni: 'Nicaragua', cu: 'Kuba', br: 'Brasilien', hn: 'Honduras', mx: 'Mexiko', ec: 'Ecuador' },
  en: { ni: 'Nicaragua', cu: 'Cuba', br: 'Brazil', hn: 'Honduras', mx: 'Mexico', ec: 'Ecuador' },
  es: { ni: 'Nicaragua', cu: 'Cuba', br: 'Brasil', hn: 'Honduras', mx: 'México', ec: 'Ecuador' },
};

/* Per-line copy. "intro" is the collection text from the brand pages,
   "long" the product description, "notes" and "moment" are taken from it. */
export const LINE_COPY = {
  fr: {
    connecticut: {
      tag: 'Doux. Crémeux. Sans détour.',
      intro: 'Le cigare idéal pour débuter et le compagnon parfait du premier café de la journée. Une douce onctuosité, une fine sucrosité, un plaisir détendu.',
      long: 'Sa cape claire Connecticut enveloppe un assemblage finement équilibré : arômes crémeux, douceur naturelle discrète, fumée souple et ronde. Un plaisir sans détour, de la première à la dernière bouffée.',
      notes: ['Crème', 'Douceur naturelle', 'Épices délicates'],
      moment: 'Le matin, avec un café ou un cappuccino',
    },
    habano: {
      tag: 'Équilibré. Aromatique. Plein de caractère.',
      intro: 'Le cigare idéal après le déjeuner : une fumée crémeuse et des arômes chaleureux qui rappellent un rhum vieilli.',
      long: 'Une cape Habano expressive sur un assemblage parfaitement dosé. Fumée crémeuse et ample, notes boisées, douceur subtile — la transition idéale entre le cigare doux du matin et le cigare puissant du soir.',
      notes: ['Notes boisées', 'Douceur subtile', 'Rhum vieilli'],
      moment: 'Après le déjeuner, avec un rhum ou un espresso',
    },
    sumatra: {
      tag: 'Rond. Élégant. Complexe.',
      intro: 'Plus corsé que le Habano, avec des notes de cacao, de terre et une fine touche épicée. Le cigare parfait pour le café de l’après-midi.',
      long: 'Une noble cape Sumatra sur un assemblage soigneusement accordé. La fumée, crémeuse et volumineuse, déploie cacao, terre sombre et café torréfié, avant de surprendre en finale par une fine note poivrée.',
      notes: ['Cacao', 'Terre sombre', 'Café torréfié', 'Pointe poivrée'],
      moment: 'L’après-midi, avec un café ou un espresso',
    },
    maduro: {
      tag: 'Cinq ans d’affinage. Puissant. Complexe.',
      intro: 'Un cigare premium intense aux arômes d’espresso, de chocolat noir et d’épices — créé pour les soirées calmes, en compagnie d’un grand whisky.',
      long: 'Un cigare pour les moments d’exception. Cinq années de maturation lui donnent une complexité rare et un équilibre remarquable : fumée dense, épices intenses, espresso, cacao noir et bois noble, pour une longue finale élégante.',
      notes: ['Espresso', 'Cacao noir', 'Bois noble', 'Épices'],
      moment: 'Le soir, avec un whisky vieilli',
    },
  },
  de: {
    connecticut: {
      tag: 'Mild. Cremig. Unkompliziert.',
      intro: 'Die perfekte Einsteigerzigarre und der ideale Begleiter zum ersten Kaffee des Tages. Sanfte Cremigkeit, feine Süsse und entspannter Genuss.',
      long: 'Das helle Connecticut-Deckblatt umhüllt eine fein abgestimmte Tabakmischung mit cremigen Aromen, dezenter natürlicher Süsse und angenehmer Balance. Weicher, vollmundiger Rauch – unkompliziert vom ersten bis zum letzten Zug.',
      notes: ['Cremig', 'Natürliche Süsse', 'Harmonische Würze'],
      moment: 'Am Morgen, zu Kaffee oder Cappuccino',
    },
    habano: {
      tag: 'Ausgewogen. Aromatisch. Charaktervoll.',
      intro: 'Die ideale Zigarre nach dem Mittagessen mit cremigem Rauch und warmen Aromen, die an gereiften Rum erinnern.',
      long: 'Ein ausdrucksstarkes Habano-Deckblatt über einer perfekt abgestimmten Mischung. Cremiger Rauch mit vollem Volumen, feine Holznoten und dezente Süsse – der ideale Übergang zwischen milder Morgen- und kräftiger Abendzigarre.',
      notes: ['Feine Holznoten', 'Dezente Süsse', 'Gereifter Rum'],
      moment: 'Nach dem Mittagessen, zu Rum oder Espresso',
    },
    sumatra: {
      tag: 'Vollmundig. Elegant. Vielschichtig.',
      intro: 'Kräftiger als die Habano, mit Noten von Kakao, Erde und einer feinen Würze. Die perfekte Zigarre für den Nachmittagskaffee.',
      long: 'Ein edles Sumatra-Deckblatt über einer sorgfältig abgestimmten Mischung. Der cremige, voluminöse Rauch entfaltet Kakao, dunkle Erde und gerösteten Kaffee – und überrascht zum Schluss mit einer feinen Pfeffernote.',
      notes: ['Kakao', 'Dunkle Erde', 'Gerösteter Kaffee', 'Feine Pfeffernote'],
      moment: 'Am Nachmittag, zu Kaffee oder Espresso',
    },
    maduro: {
      tag: 'Fünf Jahre gereift. Kraftvoll. Komplex.',
      intro: 'Eine intensive Premium-Zigarre mit Aromen von Espresso, dunkler Schokolade und Gewürzen – geschaffen für den ruhigen Abend und die Begleitung eines hochwertigen Whiskys.',
      long: 'Eine Zigarre für besondere Momente. Fünf Jahre Reifezeit verleihen ihr aussergewöhnliche Komplexität und Balance: dichter Rauch, intensive Würze, Espresso, dunkler Kakao und edles Holz – mit langem, elegantem Nachklang.',
      notes: ['Espresso', 'Dunkler Kakao', 'Edles Holz', 'Würze'],
      moment: 'Am Abend, zu einem gereiften Whisky',
    },
  },
  en: {
    connecticut: {
      tag: 'Mild. Creamy. Effortless.',
      intro: 'The perfect cigar to start with, and the ideal companion to the first coffee of the day. Gentle creaminess, a fine sweetness, relaxed enjoyment.',
      long: 'Its light Connecticut wrapper enfolds a finely balanced blend: creamy aromas, a subtle natural sweetness, a soft and rounded smoke. Easy pleasure from the first draw to the last.',
      notes: ['Cream', 'Natural sweetness', 'Delicate spice'],
      moment: 'In the morning, with a coffee or a cappuccino',
    },
    habano: {
      tag: 'Balanced. Aromatic. Full of character.',
      intro: 'The ideal cigar after lunch: a creamy smoke and warm aromas reminiscent of aged rum.',
      long: 'An expressive Habano wrapper over a perfectly judged blend. Creamy, generous smoke, woody notes and a subtle sweetness — the ideal bridge between a mild morning cigar and a strong evening one.',
      notes: ['Woody notes', 'Subtle sweetness', 'Aged rum'],
      moment: 'After lunch, with a rum or an espresso',
    },
    sumatra: {
      tag: 'Full. Elegant. Layered.',
      intro: 'Stronger than the Habano, with notes of cocoa, earth and a fine spice. The perfect cigar for the afternoon coffee.',
      long: 'A noble Sumatra wrapper over a carefully tuned blend. The creamy, voluminous smoke opens on cocoa, dark earth and roasted coffee, then surprises with a fine peppery note on the finish.',
      notes: ['Cocoa', 'Dark earth', 'Roasted coffee', 'Hint of pepper'],
      moment: 'In the afternoon, with a coffee or an espresso',
    },
    maduro: {
      tag: 'Five years aged. Powerful. Complex.',
      intro: 'An intense premium cigar with aromas of espresso, dark chocolate and spice — made for quiet evenings and a fine whisky.',
      long: 'A cigar for special moments. Five years of ageing give it rare complexity and remarkable balance: dense smoke, intense spice, espresso, dark cocoa and noble wood, with a long, elegant finish.',
      notes: ['Espresso', 'Dark cocoa', 'Noble wood', 'Spice'],
      moment: 'In the evening, with an aged whisky',
    },
  },
  es: {
    connecticut: {
      tag: 'Suave. Cremoso. Sin complicaciones.',
      intro: 'El cigarro ideal para empezar y el compañero perfecto del primer café del día. Cremosidad suave, un dulzor delicado y un placer relajado.',
      long: 'Su capa clara Connecticut envuelve una liga finamente equilibrada: aromas cremosos, un sutil dulzor natural y un humo suave y redondo. Placer sencillo de la primera a la última calada.',
      notes: ['Crema', 'Dulzor natural', 'Especias delicadas'],
      moment: 'Por la mañana, con un café o un capuchino',
    },
    habano: {
      tag: 'Equilibrado. Aromático. Con carácter.',
      intro: 'El cigarro ideal después del almuerzo: un humo cremoso y aromas cálidos que recuerdan al ron añejo.',
      long: 'Una capa Habano expresiva sobre una liga perfectamente medida. Humo cremoso y amplio, notas de madera y un dulzor sutil: la transición ideal entre el cigarro suave de la mañana y el potente de la noche.',
      notes: ['Notas de madera', 'Dulzor sutil', 'Ron añejo'],
      moment: 'Después del almuerzo, con un ron o un espresso',
    },
    sumatra: {
      tag: 'Redondo. Elegante. Complejo.',
      intro: 'Más intenso que el Habano, con notas de cacao, tierra y un toque especiado. El cigarro perfecto para el café de la tarde.',
      long: 'Una noble capa Sumatra sobre una liga cuidadosamente afinada. El humo, cremoso y voluminoso, despliega cacao, tierra oscura y café tostado, y sorprende al final con una fina nota de pimienta.',
      notes: ['Cacao', 'Tierra oscura', 'Café tostado', 'Toque de pimienta'],
      moment: 'Por la tarde, con un café o un espresso',
    },
    maduro: {
      tag: 'Cinco años de añejamiento. Potente. Complejo.',
      intro: 'Un cigarro premium intenso con aromas de espresso, chocolate negro y especias, creado para las noches tranquilas en compañía de un buen whisky.',
      long: 'Un cigarro para momentos especiales. Cinco años de maduración le dan una complejidad poco común y un equilibrio notable: humo denso, especias intensas, espresso, cacao oscuro y maderas nobles, con un final largo y elegante.',
      notes: ['Espresso', 'Cacao oscuro', 'Maderas nobles', 'Especias'],
      moment: 'Por la noche, con un whisky añejo',
    },
  },
};

export const T = {
  fr: {
    'meta.title': 'Cigares Casa Hurtado — Cigares du Nicaragua, directement de l’origine',
    'meta.desc': 'Cigares premium roulés à la main à Estelí, Nicaragua. Quatre lignes — Connecticut, Habano, Sumatra, Maduro Natural — en exclusivité en Suisse. Livraison dans toute la Suisse.',
    'nav.sub': 'Cigares du Nicaragua',
    'gate.eyebrow': 'Cigares Casa Hurtado',
    'gate.title': 'Avez-vous <em>18 ans</em> ou plus ?',
    'gate.text': 'Les cigares sont des produits de plaisir destinés aux adultes. L’accès à ce site est réservé aux personnes majeures.',
    'gate.yes': 'Oui, j’ai 18 ans',
    'gate.no': 'Non',
    'gate.denied': 'Nous sommes désolés — ce site est réservé aux personnes de 18 ans et plus.',
    'nav.lines': 'Les lignes',
    'nav.shop': 'Vitoles & prix',
    'nav.craft': 'Manufacture',
    'nav.carlos': 'Carlos Hurtado',
    'nav.contact': 'Contact',
    'nav.cta': 'Boutique',
    'hero.eyebrow': 'Estelí, Nicaragua <span>—</span> Renens, Suisse',
    'hero.title': 'Cigares du Nicaragua.<br><em>Directement de l’origine.</em>',
    'hero.text': 'De la graine au cigare super premium, tout est fait à la main, selon les méthodes traditionnelles, sur nos propres fincas. En exclusivité en Suisse.',
    'hero.cta1': 'Découvrir les quatre lignes',
    'hero.cta2': 'Voir les prix',
    'hero.s1': 'lignes',
    'hero.s2': 'vitoles par ligne',
    'hero.s3': 'cigares par coffret',
    'hero.scroll': 'Faire défiler',
    'marquee': ['Fincas propres', 'Graines cubaines', 'Roulés à la main', 'Fermentation naturelle', 'Estelí, Nicaragua', 'Exclusivité suisse'],
    'man.eyebrow': 'Casa Hurtado — le Nicaragua à l’état pur',
    'man.text': 'Casa Hurtado, c’est la véritable tradition nicaraguayenne du cigare : l’artisanat, la patience et l’exigence de la plus haute qualité. Chaque feuille est choisie avec soin, fermentée naturellement, puis roulée par des torcedores expérimentés en un cigare parfaitement équilibré.',
    'man.quote': 'Notre philosophie est simple : créer des cigares dont les arômes s’intensifient et se déploient de la première à la dernière bouffée.',
    'p1.t': 'Fincas propres & graines cubaines',
    'p1.d': 'Nos cigares naissent sur nos propres fincas au Nicaragua, contrôlés de la graine au cigare fini. Des graines sélectionnées, cultivées dans des conditions climatiques idéales.',
    'p2.t': 'Savoir-faire artisanal',
    'p2.d': 'Chaque cigare est roulé à la main par des torcedores expérimentés. Un savoir transmis de génération en génération : construction parfaite, combustion régulière.',
    'p3.t': 'Un goût qui évolue',
    'p3.d': 'Nos assemblages sont composés pour que les arômes se déploient tout au long de la dégustation, avec une intensité et une profondeur croissantes jusqu’au final.',
    'col.eyebrow': 'La collection',
    'col.title': 'Quatre lignes.<br><em>Quatre moments.</em>',
    'col.strength': 'Force',
    'col.blend': 'Assemblage',
    'col.wrapper': 'Cape',
    'col.binder': 'Sous-cape',
    'col.filler': 'Tripe',
    'col.notes': 'Arômes',
    'col.moment': 'Le moment',
    'col.from': 'dès',
    'col.single': 'la pièce',
    'col.see': 'Voir les 7 vitoles',
    'ana.eyebrow': 'Anatomie',
    'ana.title': 'Trois feuilles.<br><em>Une seule main.</em>',
    'ana.text': 'Un cigare Casa Hurtado se compose de trois étages de tabac, assemblés et roulés à la main par un torcedor.',
    'ana.wrapper': 'Cape',
    'ana.wrapper.d': 'La feuille extérieure, choisie pour sa beauté. Elle donne au cigare son allure et une grande part de ses arômes.',
    'ana.binder': 'Sous-cape',
    'ana.binder.d': 'Elle maintient la tripe et garantit une combustion régulière.',
    'ana.filler': 'Tripe',
    'ana.filler.d': 'Le cœur du cigare : l’assemblage de feuilles qui en définit la force et le caractère.',
    'ana.band': 'Bague',
    'ana.band.d': 'Le scorpion couronné de Casa Hurtado, dans la couleur de chaque ligne.',
    'ana.table': 'Origine des feuilles',
    'shop.eyebrow': 'Vitoles & prix',
    'shop.title': 'Sept formats.<br><em>Un seul standard.</em>',
    'shop.text': 'Chaque ligne existe en sept vitoles, à la pièce ou en coffret de 20. Prix en CHF, TVA incluse.',
    'shop.single': 'À la pièce',
    'shop.box': 'Coffret de 20',
    'shop.time': 'min',
    'shop.order': 'Commander',
    'shop.out': 'Épuisé',
    'shop.outd': 'Bientôt de retour',
    'shop.strength': 'Force',
    'shop.all': 'Toute la boutique',
    'shop.note': 'Commande et paiement sécurisés sur la boutique officielle rhums-cigares.ch',
    'craft.eyebrow': 'La manufacture',
    'craft.title': 'Estelí, <em>capitale mondiale</em> du tabac.',
    'craft.text': 'Au cœur d’Estelí, entourés de sols volcaniques fertiles et d’un climat idéal, naissent les cigares Casa Hurtado. Chacun d’eux suit un processus rigoureusement contrôlé, de la graine au cigare fini.',
    'craft.s1.t': 'La finca',
    'craft.s1.d': 'Le tabac pousse exclusivement sur nos propres fincas, dans les vallées fertiles du Nicaragua. Sols volcaniques et climat idéal : la base de feuilles exceptionnelles.',
    'craft.s2.t': 'La fermentation',
    'craft.s2.d': 'Après la récolte, les feuilles traversent une fermentation naturelle qui peut durer plusieurs années. C’est elle qui fait naître les arômes complexes, la texture et la profondeur.',
    'craft.s3.t': 'Les torcedores',
    'craft.s3.d': 'Des rouleurs dépositaires d’un savoir transmis de génération en génération façonnent chaque cigare à la main — pour une construction parfaite et une combustion régulière.',
    'craft.s4.t': 'Le contrôle',
    'craft.s4.d': 'Sous la direction de Carlos Hurtado, une équipe expérimentée veille à ce que chaque cigare réponde aux plus hautes exigences de qualité.',
    'carlos.eyebrow': 'Le fondateur',
    'carlos.title': 'La vision de<br><em>Carlos Hurtado.</em>',
    'carlos.p1': 'Derrière Casa Hurtado se trouve Carlos Hurtado, fondateur et force motrice de la marque. Passionné de cigares d’exception et intransigeant sur la qualité, il a créé une marque qui s’adresse aux connaisseurs comme aux amateurs.',
    'carlos.p2': 'Sa vision : un cigare non seulement parfait sur le plan artisanal, mais qui offre aussi une expérience sensorielle inimitable.',
    'carlos.h': 'Un vrai morceau de Nicaragua.',
    'carlos.p3': 'Chaque cigare Casa Hurtado est plus qu’un produit : l’expression de la culture nicaraguayenne, de ses femmes et de ses hommes, et d’une tradition du tabac cultivée depuis des décennies.',
    'carlos.sig': 'Fondateur, Cigares Casa Hurtado',
    'rit.eyebrow': 'Le rituel',
    'rit.title': 'Un cigare pour <em>chaque heure</em> du jour.',
    'rit.m1': 'Matin', 'rit.m2': 'Après le déjeuner', 'rit.m3': 'Après-midi', 'rit.m4': 'Soir',
    'gift.eyebrow': 'Offrir',
    'gift.title': 'Offrez du <em>plaisir.</em>',
    'gift.text': 'Avec l’un de nos cigares, vous faites plaisir à tous les amateurs. Chaque vitole existe en coffret de 20 cigares.',
    'gift.from': 'Coffrets dès',
    'gift.cta': 'Choisir un coffret',
    'svc.1.t': 'Livraison dans toute la Suisse',
    'svc.1.d': 'Standard CHF 9.00 · Express CHF 20.00. Expédition sous 1 à 3 jours ouvrables après réception du paiement.',
    'svc.2.t': 'Paiement',
    'svc.2.d': 'Cartes de crédit, TWINT ou virement bancaire (prépaiement).',
    'svc.3.t': 'Conservation optimale',
    'svc.3.d': 'Tous nos cigares sont stockés dans des conditions climatiques optimales jusqu’à leur expédition.',
    'svc.4.t': 'Réservé aux 18 ans et plus',
    'svc.4.d': 'La vente de produits du tabac est exclusivement réservée aux personnes majeures.',
    'contact.eyebrow': 'Contact',
    'contact.title': 'Parlons <em>cigares.</em>',
    'contact.text': 'Une question sur une ligne, une commande pour un événement ou un cadeau ? Carlos vous répond personnellement.',
    'contact.addr': 'Adresse',
    'contact.phone': 'Téléphone',
    'contact.mail': 'E-mail',
    'contact.route': 'Itinéraire',
    'form.name': 'Nom',
    'form.email': 'E-mail',
    'form.msg': 'Votre message',
    'form.send': 'Envoyer le message',
    'form.hint': 'Ouvre votre messagerie avec le message prêt à partir.',
    'form.subject': 'Demande via le site',
    'foot.tag': 'Cigares du Nicaragua. En exclusivité en Suisse.',
    'foot.lines': 'Les lignes',
    'foot.house': 'La maison',
    'foot.legal': 'Informations légales',
    'foot.cgv': 'Conditions générales',
    'foot.imp': 'Mentions légales',
    'foot.privacy': 'Protection des données',
    'foot.warn': 'Vente réservée aux personnes de 18 ans et plus. Fumer nuit gravement à votre santé et à celle de votre entourage.',
    'foot.entity': 'Rhums & Cigares Hurtado Mercado Carlos · Entreprise individuelle · Renens VD',
  },
  de: {
    'meta.title': 'Cigares Casa Hurtado — Zigarren aus Nicaragua, direkt vom Ursprung',
    'meta.desc': 'Handgerollte Premium-Zigarren aus Estelí, Nicaragua. Vier Linien – Connecticut, Habano, Sumatra, Maduro Natural – exklusiv in der Schweiz. Lieferung in die ganze Schweiz.',
    'nav.sub': 'Zigarren aus Nicaragua',
    'gate.eyebrow': 'Cigares Casa Hurtado',
    'gate.title': 'Sind Sie mindestens <em>18 Jahre</em> alt?',
    'gate.text': 'Zigarren sind Genussmittel für Erwachsene. Für den Zugriff auf diese Seite müssen Sie mindestens 18 Jahre alt sein.',
    'gate.yes': 'Ja, ich bin 18+',
    'gate.no': 'Nein',
    'gate.denied': 'Es tut uns leid – diese Seite ist Personen ab 18 Jahren vorbehalten.',
    'nav.lines': 'Die Linien',
    'nav.shop': 'Formate & Preise',
    'nav.craft': 'Manufaktur',
    'nav.carlos': 'Carlos Hurtado',
    'nav.contact': 'Kontakt',
    'nav.cta': 'Shop',
    'hero.eyebrow': 'Estelí, Nicaragua <span>—</span> Renens, Schweiz',
    'hero.title': 'Zigarren aus Nicaragua.<br><em>Direkt vom Ursprung.</em>',
    'hero.text': 'Vom Samen bis zur Super-Premium-Zigarre – alles in reiner Handarbeit, nach traditionellen Methoden, auf unseren eigenen Fincas. Exklusiv in der Schweiz.',
    'hero.cta1': 'Die vier Linien entdecken',
    'hero.cta2': 'Preise ansehen',
    'hero.s1': 'Linien',
    'hero.s2': 'Formate pro Linie',
    'hero.s3': 'Zigarren pro Box',
    'hero.scroll': 'Scrollen',
    'marquee': ['Eigene Fincas', 'Kubanische Samen', 'Von Hand gerollt', 'Natürliche Fermentation', 'Estelí, Nicaragua', 'Exklusiv in der Schweiz'],
    'man.eyebrow': 'Casa Hurtado – Nicaragua pur',
    'man.text': 'Casa Hurtado steht für echte nicaraguanische Zigarren-Tradition: Handwerk, Geduld und höchste Qualität. Jedes Blatt wird sorgfältig ausgewählt, natürlich fermentiert und erst dann von erfahrenen Torcedores zu einer perfekt ausbalancierten Zigarre verarbeitet.',
    'man.quote': 'Unsere Philosophie ist einfach: Zigarren kreieren, deren Aromen sich vom ersten bis zum letzten Zug intensivieren und entfalten.',
    'p1.t': 'Eigene Fincas & kubanische Samen',
    'p1.d': 'Unsere Zigarren entstehen auf eigenen Fincas in Nicaragua – vom Samen bis zur fertigen Zigarre vollständig kontrolliert. Ausgewählte Samen, kultiviert unter idealen klimatischen Bedingungen.',
    'p2.t': 'Handwerkliche Expertise',
    'p2.d': 'Jede Zigarre wird von erfahrenen Torcedores von Hand gefertigt. Über Generationen weitergegebenes Wissen: perfekte Konstruktion, gleichmässiges Abbrennen.',
    'p3.t': 'Geschmack, der sich entwickelt',
    'p3.d': 'Unsere Zigarren sind so komponiert, dass sich ihre Aromen stetig entfalten – vom ersten Zug bis zum Finale mit zunehmender Intensität und Tiefe.',
    'col.eyebrow': 'Die Kollektion',
    'col.title': 'Vier Linien.<br><em>Vier Momente.</em>',
    'col.strength': 'Stärke',
    'col.blend': 'Tabakmischung',
    'col.wrapper': 'Deckblatt',
    'col.binder': 'Umblatt',
    'col.filler': 'Einlage',
    'col.notes': 'Aromen',
    'col.moment': 'Der Moment',
    'col.from': 'ab',
    'col.single': 'pro Stück',
    'col.see': 'Alle 7 Formate',
    'ana.eyebrow': 'Anatomie',
    'ana.title': 'Drei Blätter.<br><em>Eine Hand.</em>',
    'ana.text': 'Eine Casa Hurtado Zigarre besteht aus drei Tabakschichten, von einem Torcedor zusammengefügt und von Hand gerollt.',
    'ana.wrapper': 'Deckblatt',
    'ana.wrapper.d': 'Das äussere Blatt, ausgewählt für seine Schönheit. Es prägt Erscheinung und einen grossen Teil der Aromen.',
    'ana.binder': 'Umblatt',
    'ana.binder.d': 'Hält die Einlage zusammen und sorgt für ein gleichmässiges Abbrennen.',
    'ana.filler': 'Einlage',
    'ana.filler.d': 'Das Herz der Zigarre: die Blattmischung, die Stärke und Charakter bestimmt.',
    'ana.band': 'Bauchbinde',
    'ana.band.d': 'Der gekrönte Skorpion von Casa Hurtado – in der Farbe jeder Linie.',
    'ana.table': 'Herkunft der Blätter',
    'shop.eyebrow': 'Formate & Preise',
    'shop.title': 'Sieben Formate.<br><em>Ein Anspruch.</em>',
    'shop.text': 'Jede Linie gibt es in sieben Formaten, als Einzelzigarre oder in der 20er Box. Preise in CHF inkl. MwSt.',
    'shop.single': 'Einzelzigarre',
    'shop.box': '20er Box',
    'shop.time': 'Min.',
    'shop.order': 'Bestellen',
    'shop.out': 'Nicht vorrätig',
    'shop.outd': 'Bald wieder da',
    'shop.strength': 'Stärke',
    'shop.all': 'Zum ganzen Shop',
    'shop.note': 'Bestellung und Zahlung sicher im offiziellen Shop rhums-cigares.ch',
    'craft.eyebrow': 'Die Manufaktur',
    'craft.title': 'Estelí, die <em>Welthauptstadt</em> des Tabaks.',
    'craft.text': 'Im Herzen von Estelí, umgeben von fruchtbaren Vulkanböden und einem idealen Klima, entstehen die Zigarren von Casa Hurtado – in einem sorgfältig kontrollierten Prozess, vom Samen bis zur fertigen Zigarre.',
    'craft.s1.t': 'Die Finca',
    'craft.s1.d': 'Der Tabak wächst exklusiv auf den eigenen Fincas in den fruchtbaren Tälern Nicaraguas. Vulkanische Böden und ideales Klima bilden das Fundament für aussergewöhnliche Blätter.',
    'craft.s2.t': 'Die Fermentation',
    'craft.s2.d': 'Nach der Ernte durchlaufen die Blätter einen natürlichen Fermentationsprozess, der mehrere Jahre dauern kann. Erst dadurch entstehen komplexe Aromen, Textur und Tiefe.',
    'craft.s3.t': 'Die Torcedores',
    'craft.s3.d': 'Zigarrenroller mit über Generationen weitergegebenem Wissen formen jede einzelne Zigarre von Hand – für perfekte Konstruktion und gleichmässiges Abbrennen.',
    'craft.s4.t': 'Die Kontrolle',
    'craft.s4.d': 'Unter der Leitung von Carlos Hurtado stellt ein erfahrenes Team sicher, dass jede Zigarre den höchsten Qualitätsstandards entspricht.',
    'carlos.eyebrow': 'Der Gründer',
    'carlos.title': 'Die Vision von<br><em>Carlos Hurtado.</em>',
    'carlos.p1': 'Hinter Casa Hurtado steht Carlos Hurtado, Gründer und treibende Kraft der Marke. Mit seiner Leidenschaft für hochwertige Zigarren und seinem Anspruch an kompromisslose Qualität hat er eine Marke geschaffen, die sich an Kenner und Liebhaber richtet.',
    'carlos.p2': 'Seine Vision: eine Zigarre, die nicht nur handwerklich perfekt ist, sondern auch ein unverwechselbares sensorisches Erlebnis bietet.',
    'carlos.h': 'Ein echtes Stück Nicaragua.',
    'carlos.p3': 'Jede Casa Hurtado Zigarre ist mehr als ein Produkt – sie ist Ausdruck der nicaraguanischen Kultur, der Menschen und der jahrzehntelangen Tradition des Tabakanbaus.',
    'carlos.sig': 'Gründer, Cigares Casa Hurtado',
    'rit.eyebrow': 'Das Ritual',
    'rit.title': 'Eine Zigarre für <em>jede Stunde</em> des Tages.',
    'rit.m1': 'Morgen', 'rit.m2': 'Nach dem Mittagessen', 'rit.m3': 'Nachmittag', 'rit.m4': 'Abend',
    'gift.eyebrow': 'Schenken',
    'gift.title': 'Schenken Sie <em>Genuss.</em>',
    'gift.text': 'Mit einer unserer Zigarren machen Sie allen Geniessern eine Freude. Jedes Format gibt es in der 20er Box.',
    'gift.from': 'Boxen ab',
    'gift.cta': 'Box auswählen',
    'svc.1.t': 'Lieferung in die ganze Schweiz',
    'svc.1.d': 'Standard CHF 9.00 · Express CHF 20.00. Versand innerhalb von 1–3 Werktagen nach Zahlungseingang.',
    'svc.2.t': 'Zahlung',
    'svc.2.d': 'Kreditkarten, TWINT oder direkte Banküberweisung (Vorauskasse).',
    'svc.3.t': 'Optimal gelagert',
    'svc.3.d': 'Alle Zigarren werden bis zum Versand unter optimalen klimatischen Bedingungen gelagert.',
    'svc.4.t': 'Ab 18 Jahren',
    'svc.4.d': 'Der Verkauf von Tabakwaren erfolgt ausschliesslich an Personen ab 18 Jahren.',
    'contact.eyebrow': 'Kontakt',
    'contact.title': 'Reden wir über <em>Zigarren.</em>',
    'contact.text': 'Eine Frage zu einer Linie, eine Bestellung für einen Anlass oder ein Geschenk? Carlos antwortet Ihnen persönlich.',
    'contact.addr': 'Adresse',
    'contact.phone': 'Telefon',
    'contact.mail': 'E-Mail',
    'contact.route': 'Route planen',
    'form.name': 'Name',
    'form.email': 'E-Mail',
    'form.msg': 'Ihre Nachricht',
    'form.send': 'Nachricht senden',
    'form.hint': 'Öffnet Ihr E-Mail-Programm mit der fertigen Nachricht.',
    'form.subject': 'Anfrage über die Website',
    'foot.tag': 'Zigarren aus Nicaragua. Exklusiv in der Schweiz.',
    'foot.lines': 'Die Linien',
    'foot.house': 'Das Haus',
    'foot.legal': 'Rechtliches',
    'foot.cgv': 'AGB',
    'foot.imp': 'Impressum',
    'foot.privacy': 'Datenschutz',
    'foot.warn': 'Verkauf nur an Personen ab 18 Jahren. Rauchen gefährdet die Gesundheit.',
    'foot.entity': 'Rhums & Cigares Hurtado Mercado Carlos · Einzelfirma · Renens VD',
  },
  en: {
    'meta.title': 'Cigares Casa Hurtado — Cigars from Nicaragua, straight from the source',
    'meta.desc': 'Premium cigars hand-rolled in Estelí, Nicaragua. Four lines — Connecticut, Habano, Sumatra, Maduro Natural — exclusively in Switzerland. Delivery throughout Switzerland.',
    'nav.sub': 'Cigars from Nicaragua',
    'gate.eyebrow': 'Cigares Casa Hurtado',
    'gate.title': 'Are you <em>18</em> or older?',
    'gate.text': 'Cigars are products of enjoyment intended for adults. Access to this website is reserved for people aged 18 and over.',
    'gate.yes': 'Yes, I am 18+',
    'gate.no': 'No',
    'gate.denied': 'We are sorry — this website is reserved for people aged 18 and over.',
    'nav.lines': 'The lines',
    'nav.shop': 'Sizes & prices',
    'nav.craft': 'Factory',
    'nav.carlos': 'Carlos Hurtado',
    'nav.contact': 'Contact',
    'nav.cta': 'Shop',
    'hero.eyebrow': 'Estelí, Nicaragua <span>—</span> Renens, Switzerland',
    'hero.title': 'Cigars from Nicaragua.<br><em>Straight from the source.</em>',
    'hero.text': 'From seed to super-premium cigar, everything is made by hand, using traditional methods, on our own fincas. Exclusively in Switzerland.',
    'hero.cta1': 'Discover the four lines',
    'hero.cta2': 'See prices',
    'hero.s1': 'lines',
    'hero.s2': 'sizes per line',
    'hero.s3': 'cigars per box',
    'hero.scroll': 'Scroll',
    'marquee': ['Our own fincas', 'Cuban seeds', 'Rolled by hand', 'Natural fermentation', 'Estelí, Nicaragua', 'Exclusive to Switzerland'],
    'man.eyebrow': 'Casa Hurtado — pure Nicaragua',
    'man.text': 'Casa Hurtado stands for true Nicaraguan cigar tradition: craftsmanship, patience and the highest standard of quality. Every leaf is carefully selected, naturally fermented, then rolled by experienced torcedores into a perfectly balanced cigar.',
    'man.quote': 'Our philosophy is simple: to create cigars whose aromas intensify and unfold from the first draw to the last.',
    'p1.t': 'Our own fincas & Cuban seeds',
    'p1.d': 'Our cigars are born on our own fincas in Nicaragua, controlled from seed to finished cigar. Selected seeds, grown in ideal climatic conditions.',
    'p2.t': 'Artisan expertise',
    'p2.d': 'Every cigar is rolled by hand by experienced torcedores. Knowledge handed down through generations: perfect construction, an even burn.',
    'p3.t': 'A taste that evolves',
    'p3.d': 'Our blends are composed so that their aromas unfold throughout the smoke, with growing intensity and depth right to the finish.',
    'col.eyebrow': 'The collection',
    'col.title': 'Four lines.<br><em>Four moments.</em>',
    'col.strength': 'Strength',
    'col.blend': 'Blend',
    'col.wrapper': 'Wrapper',
    'col.binder': 'Binder',
    'col.filler': 'Filler',
    'col.notes': 'Aromas',
    'col.moment': 'The moment',
    'col.from': 'from',
    'col.single': 'per cigar',
    'col.see': 'See all 7 sizes',
    'ana.eyebrow': 'Anatomy',
    'ana.title': 'Three leaves.<br><em>One hand.</em>',
    'ana.text': 'A Casa Hurtado cigar is made of three layers of tobacco, assembled and rolled by hand by a torcedor.',
    'ana.wrapper': 'Wrapper',
    'ana.wrapper.d': 'The outer leaf, chosen for its beauty. It gives the cigar its look and much of its aroma.',
    'ana.binder': 'Binder',
    'ana.binder.d': 'It holds the filler together and ensures an even burn.',
    'ana.filler': 'Filler',
    'ana.filler.d': 'The heart of the cigar: the blend of leaves that defines its strength and character.',
    'ana.band': 'Band',
    'ana.band.d': 'The crowned scorpion of Casa Hurtado, in the colour of each line.',
    'ana.table': 'Origin of the leaves',
    'shop.eyebrow': 'Sizes & prices',
    'shop.title': 'Seven sizes.<br><em>One standard.</em>',
    'shop.text': 'Every line comes in seven sizes, as a single cigar or in a box of 20. Prices in CHF, VAT included.',
    'shop.single': 'Single cigar',
    'shop.box': 'Box of 20',
    'shop.time': 'min',
    'shop.order': 'Order',
    'shop.out': 'Sold out',
    'shop.outd': 'Back soon',
    'shop.strength': 'Strength',
    'shop.all': 'Full shop',
    'shop.note': 'Secure ordering and payment on the official shop rhums-cigares.ch (in French or German)',
    'craft.eyebrow': 'The factory',
    'craft.title': 'Estelí, <em>world capital</em> of tobacco.',
    'craft.text': 'In the heart of Estelí, surrounded by fertile volcanic soil and an ideal climate, Casa Hurtado cigars are born — each one following a carefully controlled process, from seed to finished cigar.',
    'craft.s1.t': 'The finca',
    'craft.s1.d': 'Our tobacco grows exclusively on our own fincas, in the fertile valleys of Nicaragua. Volcanic soil and an ideal climate: the foundation of exceptional leaves.',
    'craft.s2.t': 'Fermentation',
    'craft.s2.d': 'After the harvest, the leaves go through a natural fermentation that can last several years. It is what creates the complex aromas, the texture and the depth.',
    'craft.s3.t': 'The torcedores',
    'craft.s3.d': 'Rollers carrying knowledge handed down through generations shape every single cigar by hand — for perfect construction and an even burn.',
    'craft.s4.t': 'Quality control',
    'craft.s4.d': 'Under the direction of Carlos Hurtado, an experienced team makes sure every cigar meets the highest quality standards.',
    'carlos.eyebrow': 'The founder',
    'carlos.title': 'The vision of<br><em>Carlos Hurtado.</em>',
    'carlos.p1': 'Behind Casa Hurtado is Carlos Hurtado, founder and driving force of the brand. With his passion for fine cigars and his demand for uncompromising quality, he created a brand for connoisseurs and enthusiasts alike.',
    'carlos.p2': 'His vision: a cigar that is not only perfect in its craftsmanship, but also offers an unmistakable sensory experience.',
    'carlos.h': 'A true piece of Nicaragua.',
    'carlos.p3': 'Every Casa Hurtado cigar is more than a product — it is an expression of Nicaraguan culture, of its people and of a tobacco-growing tradition decades in the making.',
    'carlos.sig': 'Founder, Cigares Casa Hurtado',
    'rit.eyebrow': 'The ritual',
    'rit.title': 'A cigar for <em>every hour</em> of the day.',
    'rit.m1': 'Morning', 'rit.m2': 'After lunch', 'rit.m3': 'Afternoon', 'rit.m4': 'Evening',
    'gift.eyebrow': 'Gifting',
    'gift.title': 'Give the gift of <em>pleasure.</em>',
    'gift.text': 'One of our cigars will delight any aficionado. Every size is available in a box of 20 cigars.',
    'gift.from': 'Boxes from',
    'gift.cta': 'Choose a box',
    'svc.1.t': 'Delivery throughout Switzerland',
    'svc.1.d': 'Standard CHF 9.00 · Express CHF 20.00. Shipped within 1–3 working days of payment.',
    'svc.2.t': 'Payment',
    'svc.2.d': 'Credit cards, TWINT or bank transfer (prepayment).',
    'svc.3.t': 'Perfectly stored',
    'svc.3.d': 'All our cigars are kept in optimal climatic conditions until they are shipped.',
    'svc.4.t': 'Adults only (18+)',
    'svc.4.d': 'Tobacco products are sold exclusively to people aged 18 and over.',
    'contact.eyebrow': 'Contact',
    'contact.title': 'Let’s talk <em>cigars.</em>',
    'contact.text': 'A question about a line, an order for an event or a gift? Carlos will answer you personally.',
    'contact.addr': 'Address',
    'contact.phone': 'Phone',
    'contact.mail': 'Email',
    'contact.route': 'Directions',
    'form.name': 'Name',
    'form.email': 'Email',
    'form.msg': 'Your message',
    'form.send': 'Send message',
    'form.hint': 'Opens your email app with the message ready to send.',
    'form.subject': 'Enquiry from the website',
    'foot.tag': 'Cigars from Nicaragua. Exclusively in Switzerland.',
    'foot.lines': 'The lines',
    'foot.house': 'The house',
    'foot.legal': 'Legal',
    'foot.cgv': 'Terms & conditions',
    'foot.imp': 'Legal notice',
    'foot.privacy': 'Privacy policy',
    'foot.warn': 'Sale restricted to people aged 18 and over. Smoking seriously harms your health and the health of those around you.',
    'foot.entity': 'Rhums & Cigares Hurtado Mercado Carlos · Sole proprietorship · Renens VD',
  },
  es: {
    'meta.title': 'Cigares Casa Hurtado — Cigarros de Nicaragua, directamente del origen',
    'meta.desc': 'Cigarros premium torcidos a mano en Estelí, Nicaragua. Cuatro líneas — Connecticut, Habano, Sumatra, Maduro Natural — en exclusiva en Suiza. Envío a toda Suiza.',
    'nav.sub': 'Cigarros de Nicaragua',
    'gate.eyebrow': 'Cigares Casa Hurtado',
    'gate.title': '¿Tiene <em>18 años</em> o más?',
    'gate.text': 'Los cigarros son productos de placer destinados a adultos. El acceso a este sitio está reservado a personas mayores de edad.',
    'gate.yes': 'Sí, tengo 18 años',
    'gate.no': 'No',
    'gate.denied': 'Lo sentimos: este sitio está reservado a personas de 18 años o más.',
    'nav.lines': 'Las líneas',
    'nav.shop': 'Vitolas y precios',
    'nav.craft': 'Fábrica',
    'nav.carlos': 'Carlos Hurtado',
    'nav.contact': 'Contacto',
    'nav.cta': 'Tienda',
    'hero.eyebrow': 'Estelí, Nicaragua <span>—</span> Renens, Suiza',
    'hero.title': 'Cigarros de Nicaragua.<br><em>Directamente del origen.</em>',
    'hero.text': 'De la semilla al cigarro súper premium, todo se hace a mano, con métodos tradicionales, en nuestras propias fincas. En exclusiva en Suiza.',
    'hero.cta1': 'Descubrir las cuatro líneas',
    'hero.cta2': 'Ver precios',
    'hero.s1': 'líneas',
    'hero.s2': 'vitolas por línea',
    'hero.s3': 'cigarros por caja',
    'hero.scroll': 'Desplazar',
    'marquee': ['Fincas propias', 'Semillas cubanas', 'Torcidos a mano', 'Fermentación natural', 'Estelí, Nicaragua', 'Exclusiva en Suiza'],
    'man.eyebrow': 'Casa Hurtado — Nicaragua en estado puro',
    'man.text': 'Casa Hurtado es la auténtica tradición tabaquera nicaragüense: artesanía, paciencia y la máxima exigencia de calidad. Cada hoja se selecciona con cuidado, se fermenta de forma natural y después la tuercen torcedores experimentados hasta lograr un cigarro perfectamente equilibrado.',
    'man.quote': 'Nuestra filosofía es sencilla: crear cigarros cuyos aromas se intensifican y se despliegan de la primera a la última calada.',
    'p1.t': 'Fincas propias y semillas cubanas',
    'p1.d': 'Nuestros cigarros nacen en nuestras propias fincas en Nicaragua, controlados de la semilla al cigarro terminado. Semillas seleccionadas, cultivadas en condiciones climáticas ideales.',
    'p2.t': 'Maestría artesanal',
    'p2.d': 'Cada cigarro lo tuercen a mano torcedores experimentados. Un saber transmitido de generación en generación: construcción perfecta y combustión uniforme.',
    'p3.t': 'Un sabor que evoluciona',
    'p3.d': 'Nuestras ligas están compuestas para que los aromas se desplieguen durante toda la fumada, con una intensidad y una profundidad crecientes hasta el final.',
    'col.eyebrow': 'La colección',
    'col.title': 'Cuatro líneas.<br><em>Cuatro momentos.</em>',
    'col.strength': 'Fuerza',
    'col.blend': 'Liga',
    'col.wrapper': 'Capa',
    'col.binder': 'Capote',
    'col.filler': 'Tripa',
    'col.notes': 'Aromas',
    'col.moment': 'El momento',
    'col.from': 'desde',
    'col.single': 'por unidad',
    'col.see': 'Ver las 7 vitolas',
    'ana.eyebrow': 'Anatomía',
    'ana.title': 'Tres hojas.<br><em>Una sola mano.</em>',
    'ana.text': 'Un cigarro Casa Hurtado se compone de tres niveles de tabaco, ensamblados y torcidos a mano por un torcedor.',
    'ana.wrapper': 'Capa',
    'ana.wrapper.d': 'La hoja exterior, elegida por su belleza. Da al cigarro su aspecto y gran parte de su aroma.',
    'ana.binder': 'Capote',
    'ana.binder.d': 'Sujeta la tripa y garantiza una combustión uniforme.',
    'ana.filler': 'Tripa',
    'ana.filler.d': 'El corazón del cigarro: la mezcla de hojas que define su fuerza y su carácter.',
    'ana.band': 'Anilla',
    'ana.band.d': 'El escorpión coronado de Casa Hurtado, en el color de cada línea.',
    'ana.table': 'Origen de las hojas',
    'shop.eyebrow': 'Vitolas y precios',
    'shop.title': 'Siete vitolas.<br><em>Una sola exigencia.</em>',
    'shop.text': 'Cada línea existe en siete vitolas, por unidad o en caja de 20. Precios en CHF, IVA incluido.',
    'shop.single': 'Por unidad',
    'shop.box': 'Caja de 20',
    'shop.time': 'min',
    'shop.order': 'Pedir',
    'shop.out': 'Agotado',
    'shop.outd': 'Pronto de vuelta',
    'shop.strength': 'Fuerza',
    'shop.all': 'Toda la tienda',
    'shop.note': 'Pedido y pago seguros en la tienda oficial rhums-cigares.ch (en francés o alemán)',
    'craft.eyebrow': 'La fábrica',
    'craft.title': 'Estelí, <em>capital mundial</em> del tabaco.',
    'craft.text': 'En el corazón de Estelí, rodeados de fértiles suelos volcánicos y de un clima ideal, nacen los cigarros Casa Hurtado, cada uno siguiendo un proceso rigurosamente controlado, de la semilla al cigarro terminado.',
    'craft.s1.t': 'La finca',
    'craft.s1.d': 'El tabaco crece exclusivamente en nuestras propias fincas, en los fértiles valles de Nicaragua. Suelos volcánicos y clima ideal: la base de hojas excepcionales.',
    'craft.s2.t': 'La fermentación',
    'craft.s2.d': 'Tras la cosecha, las hojas pasan por una fermentación natural que puede durar varios años. De ella nacen los aromas complejos, la textura y la profundidad.',
    'craft.s3.t': 'Los torcedores',
    'craft.s3.d': 'Torcedores con un saber transmitido de generación en generación dan forma a mano a cada cigarro, para una construcción perfecta y una combustión uniforme.',
    'craft.s4.t': 'El control',
    'craft.s4.d': 'Bajo la dirección de Carlos Hurtado, un equipo experimentado garantiza que cada cigarro cumpla los más altos estándares de calidad.',
    'carlos.eyebrow': 'El fundador',
    'carlos.title': 'La visión de<br><em>Carlos Hurtado.</em>',
    'carlos.p1': 'Detrás de Casa Hurtado está Carlos Hurtado, fundador y fuerza impulsora de la marca. Con su pasión por los cigarros de calidad y su exigencia de una calidad sin concesiones, creó una marca dirigida a conocedores y aficionados.',
    'carlos.p2': 'Su visión: un cigarro que no solo sea perfecto en su elaboración, sino que ofrezca además una experiencia sensorial inconfundible.',
    'carlos.h': 'Un auténtico pedazo de Nicaragua.',
    'carlos.p3': 'Cada cigarro Casa Hurtado es más que un producto: es la expresión de la cultura nicaragüense, de su gente y de una tradición tabacalera de décadas.',
    'carlos.sig': 'Fundador, Cigares Casa Hurtado',
    'rit.eyebrow': 'El ritual',
    'rit.title': 'Un cigarro para <em>cada hora</em> del día.',
    'rit.m1': 'Mañana', 'rit.m2': 'Después del almuerzo', 'rit.m3': 'Tarde', 'rit.m4': 'Noche',
    'gift.eyebrow': 'Regalar',
    'gift.title': 'Regale <em>placer.</em>',
    'gift.text': 'Con uno de nuestros cigarros hará feliz a cualquier aficionado. Cada vitola existe en caja de 20 cigarros.',
    'gift.from': 'Cajas desde',
    'gift.cta': 'Elegir una caja',
    'svc.1.t': 'Envío a toda Suiza',
    'svc.1.d': 'Estándar CHF 9.00 · Exprés CHF 20.00. Envío en 1–3 días laborables tras recibir el pago.',
    'svc.2.t': 'Pago',
    'svc.2.d': 'Tarjetas de crédito, TWINT o transferencia bancaria (pago por adelantado).',
    'svc.3.t': 'Conservación óptima',
    'svc.3.d': 'Todos nuestros cigarros se conservan en condiciones climáticas óptimas hasta su envío.',
    'svc.4.t': 'Solo mayores de 18 años',
    'svc.4.d': 'La venta de productos de tabaco está reservada exclusivamente a mayores de edad.',
    'contact.eyebrow': 'Contacto',
    'contact.title': 'Hablemos de <em>cigarros.</em>',
    'contact.text': '¿Una pregunta sobre una línea, un pedido para un evento o un regalo? Carlos le responde personalmente.',
    'contact.addr': 'Dirección',
    'contact.phone': 'Teléfono',
    'contact.mail': 'Correo',
    'contact.route': 'Cómo llegar',
    'form.name': 'Nombre',
    'form.email': 'Correo',
    'form.msg': 'Su mensaje',
    'form.send': 'Enviar mensaje',
    'form.hint': 'Abre su programa de correo con el mensaje listo para enviar.',
    'form.subject': 'Consulta desde el sitio web',
    'foot.tag': 'Cigarros de Nicaragua. En exclusiva en Suiza.',
    'foot.lines': 'Las líneas',
    'foot.house': 'La casa',
    'foot.legal': 'Información legal',
    'foot.cgv': 'Condiciones generales',
    'foot.imp': 'Aviso legal',
    'foot.privacy': 'Protección de datos',
    'foot.warn': 'Venta reservada a mayores de 18 años. Fumar perjudica gravemente su salud y la de quienes le rodean.',
    'foot.entity': 'Rhums & Cigares Hurtado Mercado Carlos · Empresa individual · Renens VD',
  },
};
